# Generated by Django 5.1.1 on 2024-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='prayer_type',
            field=models.CharField(choices=[('UNSPOKEN', 'Unspoken Prayer Request'), ('VERBAL', 'Verbal Prayer Request'), ('HEALTH', 'Health-related Prayer Request'), ('FAMILY', 'Family-related Prayer Request'), ('GUIDANCE', 'Guidance Prayer Request'), ('PRAISE', 'Praise Report/Thanksgiving'), ('COMMUNITY', 'Community Prayer Request'), ('SPIRITUAL', 'Spiritual Growth')], default='VERBAL', max_length=20),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
