# Generated by Django 5.1.1 on 2024-09-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_requests', '0002_alter_prayerrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
